### ISSUE TITLE
Getting a Typescript error on the frontend when compiling

### ISSUE THREAD

**Issue by herbc2** [kaklakariada/aws-ec2-controller#2]
TypeScript error in aws-ec2-controller-master/frontend/src/hooks/state.tsx(16,28):
Property 'instance' is missing in type '[ReducerState, Dispatch<Action>]' but required in type 'ReducerState'.  TS2741

    14 |   const state = useReducer(reducer, initState);
    15 |   return (
  > 16 |     <StateContext.Provider value={state}>
       |                            ^
    17 |       {children}
    18 |     </StateContext.Provider>
    19 |   );

**Comment by kaklakariada** [comment]
I tried but could not fix the compile error. It worked before on my machine.
Do you know how to fix this? PR welcome!

**Comment by kaklakariada** [comment]
This should be solved with #3. However, reload is not working any more. I am working on this.
